name: Terraform AWS

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  aws-terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials A
        if: ${{ github.actor == 'KoKaTiM1' }}
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID_A }}:role/oidc-provider
          aws-region: us-east-1

      - name: Configure AWS credentials B
        if: ${{ github.actor == 'yossef-cohen' }}
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID_B }}:role/oidc-provider
          aws-region: us-east-1

      - name: Attach IAM policy
        run: |
          aws iam attach-role-policy \
            --role-name oidc-provider \
            --policy-arn arn:aws:iam::aws:policy/AdministratorAccess 2>&1 | grep -v "NoSuchEntity|EntityAlreadyExists" || true
        continue-on-error: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init
        env: 
          TF_LOG: DEBUG

      - name: Terraform Plan
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan'
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: terraform apply -input=false -auto-approve

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -input=false -auto-approve
